env:
  contexts:
    - name: "TestPHP"
      urls:
        - "http://testphp.vulnweb.com"
      includePaths:
        - "http://testphp.vulnweb.com.*"
      excludePaths:
        - "http://testphp.vulnweb.com/logout.*"
      authentication:
        method: form
        parameters:
          loginPageUrl: "http://testphp.vulnweb.com/login.php"
          loginRequestUrl: "http://testphp.vulnweb.com/login.php"
          loginRequestData: "uname=test&pass=test&btnLogin=Login"
        verification:
          method: poll
          pollUrl: "http://testphp.vulnweb.com/"
          pollFrequency: 2
          pollUnits: requests
          loggedInRegex: "Logout"
          loggedOutRegex: "Login"
      users:
        - name: "testuser"
          credentials:
            username: "test"
            password: "test"

jobs:
  - type: spider
    parameters:
      context: "TestPHP"
      user: "testuser"

  - type: activeScan
    parameters:
      context: "TestPHP"
      user: "testuser"

  - type: report
    parameters:
      template: traditional-html
      reportFile: zap_reports/report.html
      reportDir: zap_reports
      reportTitle: "TestPHP Authenticated Scan"

  - type: report
    parameters:
      template: traditional-json
      reportFile: zap_reports/report.json
      reportDir: zap_reports
      reportTitle: "TestPHP Authenticated Scan"

  - type: report
    parameters:
      template: traditional-md
      reportFile: zap_reports/report.md
      reportDir: zap_reports
      reportTitle: "TestPHP Authenticated Scan"
